#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_26  // LRC
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_25  // BCK
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_27  // DATA

#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_23  // DIN
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_33  // BCL
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_32  // LRC

#else

#define AUDIO_I2S_GPIO_WS GPIO_NUM_26
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_25
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_27
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_23

#endif

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_12
#define ASR_BUTTON_GPIO         GPIO_NUM_34
#define BUILTIN_LED_GPIO        GPIO_NUM_2

#define DISPLAY_SDA_PIN GPIO_NUM_21
#define DISPLAY_SCL_PIN GPIO_NUM_22
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  64

#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false

// RGB LED
#define RGB_LED_GPIO GPIO_NUM_13
#define RGB_LED_COUNT 12

// Fan
#define FAN_GPIO GPIO_NUM_5

// Flame Sensor
#define FLAME_SENSOR_D_GPIO GPIO_NUM_18  // 数字输出
#define FLAME_SENSOR_A_GPIO GPIO_NUM_36  // 模拟输出

// Water Pump
#define WATER_PUMP_GPIO_1 GPIO_NUM_14
#define WATER_PUMP_GPIO_2 GPIO_NUM_15

#endif // _BOARD_CONFIG_H_